version: "2.2"
services:
  postgres:
    container_name: postgres
    image:  luanmattos/atos:postgresql
    environment:
      POSTGRES_USER: square_db1
      POSTGRES_PASSWORD: J3K6051ER4u824VQP2A3I81QLO6uCCCg51zZ29H3V2KKlAWiJ3
      PGDATA: /data/postgres
      POSTGRES_DB: atos
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge