version: "2.2"
services:
  php_apache:
    container_name: php_apache
    image: luanmattos/atos:php-apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
  postgres:
      container_name: postgres
      image: luanmattos/atos:postgresql
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: eFdarksadfw4r54af4fd4a54h2fasfdg
        PGDATA: /data/postgres
        POSTGRES_DB: atos
      volumes:
        - "./data/postgres:/var/lib/postgresql/data"
      ports:
        - "5432:5432"
      networks:
        - postgres

networks:
   postgres:
      driver: bridge
   mongo:
      driver: bridge