version: "2.2"
services:
  php_apache:
    container_name: php_apache
    image: luanmattos/atos:php-apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    networks:
      - php_apache
networks:
  php_apache:
    external: true